# Site settings
title: Webb365 - Github
email: admin@webb365.se
description: "Alla projekt som 채r skapade av Webb365 presenteras p책 denna sida."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  
# Footer settings
footer:
  copyright: Webb365
  location: L채s mer p책
  social: Socialt
  credits: Tack till

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/webb365
  - title: facebook
    url: https://www.facebook.com/Webb365.se
  - title: github
    url: http://github.com/webb365

# Postal address (add as many lines as necessary)
address:
  - line: '<a href="http://webb365.se" >Webb365.se</a>'
  
# Credits content
credits: '<a href="http://startbootstrap.com" rel="nofollow">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
